# Application settings
features:
  bluesky_posting: true  # Toggle Bluesky posting on/off
  test_mode: false      # Preview posts without sending them
  limit_new_station_posts: 10  # Max number of new station posts per run (0 for unlimited)
  streetview_images: true  # Include Google Streetview images in new station posts
  force_station_id: "a3b148bf-a135-11e9-9cda-0a87ae2ba916"  # Force post Laramie Ave & Madison St station

# API settings
api:
  page_size: 1000  # Number of records per page
  max_retries: 3   # Number of retries on API failure
  timeouts:
    soda: 30       # Timeout in seconds for SODA API calls
    streetview: 10 # Timeout in seconds for Google Street View API calls

# Logging settings
logging:
  level: INFO
  format: '%(asctime)s - %(levelname)s - %(message)s'
